/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ParagraphBreakPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var ParagraphBreakPlugin = class extends import_obsidian.Plugin {
  async onload() {
    this.addCommand({
      id: "insert-paragraph-break",
      name: "Wstaw nowy akapit (Enter = nowy paragraf)",
      editorCallback: (editor) => {
        this.insertParagraphBreak(editor);
      }
    });
    this.registerDomEvent(document, "keydown", (evt) => {
      if (evt.key !== "Enter" || evt.shiftKey || evt.ctrlKey || evt.metaKey || evt.altKey) {
        return;
      }
      const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
      if (!activeView || activeView.getMode() !== "source") {
        return;
      }
      const editorEl = activeView.contentEl.querySelector(".cm-editor");
      if (!editorEl || !editorEl.contains(document.activeElement)) {
        return;
      }
      evt.preventDefault();
      evt.stopPropagation();
      this.insertParagraphBreak(activeView.editor);
    }, { capture: true });
  }
  insertParagraphBreak(editor) {
    const cursor = editor.getCursor();
    const line = editor.getLine(cursor.line);
    const totalLines = editor.lineCount();
    const listMatch = line.match(/^(\s*)([-*+]|\d+\.)\s/);
    if (listMatch) {
      const afterBullet = line.slice(listMatch[0].length);
      if (afterBullet.trim() === "") {
        editor.setLine(cursor.line, "");
        editor.replaceRange("\n", { line: cursor.line, ch: 0 }, { line: cursor.line, ch: 0 });
        editor.setCursor({ line: cursor.line + 1, ch: 0 });
      } else {
        const prefix = listMatch[0];
        const numberedMatch = line.match(/^(\s*)(\d+)(\.)\s/);
        let newPrefix = prefix;
        if (numberedMatch) {
          const num = parseInt(numberedMatch[2]) + 1;
          newPrefix = `${numberedMatch[1]}${num}${numberedMatch[3]} `;
        }
        const insertPos = { line: cursor.line, ch: cursor.ch };
        editor.replaceRange(`
${newPrefix}`, insertPos);
        editor.setCursor({ line: cursor.line + 1, ch: newPrefix.length });
      }
      return;
    }
    let inCodeBlock = false;
    for (let i = 0; i <= cursor.line; i++) {
      if (editor.getLine(i).startsWith("```")) {
        inCodeBlock = !inCodeBlock;
      }
    }
    if (inCodeBlock) {
      editor.replaceRange("\n", cursor);
      editor.setCursor({ line: cursor.line + 1, ch: 0 });
      return;
    }
    const nextLine = cursor.line < totalLines - 1 ? editor.getLine(cursor.line + 1) : null;
    const atLineEnd = cursor.ch >= line.length;
    if (atLineEnd && nextLine === "") {
      editor.setCursor({ line: cursor.line + 2, ch: 0 });
    } else {
      editor.replaceRange("\n\n", { line: cursor.line, ch: cursor.ch });
      editor.setCursor({ line: cursor.line + 2, ch: 0 });
    }
  }
  onunload() {
  }
};
